#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source my customizations
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/custom/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/custom/init.zsh"
fi
